// /*
//  * This file was generated by the Gradle 'init' task.
//  *
//  * This generated file contains a sample Java application project to get you started.
//  * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.11.1/userguide/building_java_projects.html in the Gradle documentation.
//  * This project uses @Incubating APIs which are subject to change.
//  */

// plugins {
//     // Apply the application plugin to add support for building a CLI application in Java.
//     application
// }

// repositories {
//     // Use Maven Central for resolving dependencies.
//     mavenCentral()
// }

// dependencies {
//     // This dependency is used by the application.
//     implementation(libs.guava)
// }

// testing {
//     suites {
//         // Configure the built-in test suite
//         val test by getting(JvmTestSuite::class) {
//             // Use JUnit4 test framework
//             useJUnit("4.13.2")
//         }
//     }
// }

// // Apply a specific Java toolchain to ease working on different environments.
// java {
//     toolchain {
//         languageVersion = JavaLanguageVersion.of(16)
//     }
// }

// application {
//     // Define the main class for the application.
//     mainClass = "org.example.App"
// }

plugins {
    id("org.springframework.boot") version "3.1.5"
    id("io.spring.dependency-management") version "1.1.3"
    java
}

group = "com.example"
version = "1.0.0"

repositories {
    mavenCentral()
}

dependencies {
    // Spring Boot Starter Web for REST endpoints
    implementation("org.springframework.boot:spring-boot-starter-web")

    // Dependency for handling file uploads
    implementation("org.springframework.boot:spring-boot-starter-tomcat")

    // Lombok (optional, for less boilerplate)
    implementation("org.projectlombok:lombok:1.18.28")

    // For unit testing
    testImplementation("org.springframework.boot:spring-boot-starter-test")
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17)) // Ensure you're using Java 17
    }
}

tasks.withType<Test> {
    useJUnitPlatform()
}